### ISSUE TITLE
Ability to use a image::ImageBuffer directly?

### ISSUE THREAD

**Issue by bramp** [STPR/contour_tracing#1]
Firstly thanks for this library. It worked great for a project I'm working on.

One feature request. I have a image::ImageBuffer and I'd like to pass it directly to `bits_to_paths`, instead I have to copy it into a `Vec::<Vec<i8>>`. For example:

```rust
    let mut img = GrayImage::new(width, height); // the image::ImageBuffer
    let background_color = Luma([0]); // Black
    let foreground_color = Luma([1]); // White

    contour_tracing::image_to_paths(img, background_color, true);
```

Thanks

**Comment by STPR** [comment]
Thanks for your comment and I'm glad it worked for your project 😀.

It's an interesting idea but I think it would add some problems, complexity and you will not gain a lot.
Actually, it's just 4 lines of code to add on your side, something like (not tested):
```rust
let mut bits = vec![vec![0i8; width]; height];
for p in img.pixels() {
    if p.2 == image::Luma([0]) {
        bits[p.1 as usize][p.0 as usize] = 1;
    }
}
```
The way it works and to directly use the buffer, it would need to be expanded to add a border and eventually converted to 8 bits.
Probably not impossible but I need to do some research...

**Comment by bramp** [comment]
Thanks. Yes my code looks almost like that :-) I wanted to avoid the double memory usage, and needless copies.

Ah looking at your code now, I see you also do a full copy, to add the border around it. So I guess, accepting a ImageBuffer would allow me to avoid one full copy, but you could easily still do that internally.

Either way, no worries if you don't think this is worth adding. I just figured must folks would be doing the processing on images.

**Comment by STPR** [comment]
The library do a little bit more than a simple copy, it adds a border and changes the 0 to -1 to make the rest easier to process.
It would surely be better without adding a border but rust is very strict and you can't read outside of an array or buffer without making your code unsafe...
If I find a better way to deal with the "bound checking" of rust, I will add your idea 😀.

How would you process a 1bit image knowing that you need values other than 0 or 1 ?
At one point, you necessarily need more memory.

**Comment by bramp** [comment]
Well rust vectors do have .get() which allow out of bounds and return Optional.

So something like `v.get(-1).unwrap_or(0)` will return the actual value or zero if out of bounds.

**Comment by STPR** [comment]
Thanks, I'll have a look and try that.

**Comment by STPR** [comment]
get_pixel() can't return Optional and just panic.
We can expect this in the 0.24 version of the image crate:
[https://github.com/image-rs/image/issues/1433](https://github.com/image-rs/image/issues/1433)
```
- optional get_pixel methods (and more clarity on assert vs. Result)
```

So, I've added a function single_l8_to_paths() and avoided the panics differently but it's still not optimized:
[https://docs.rs/contour_tracing/latest/contour_tracing/image/fn.single_l8_to_paths.html](https://docs.rs/contour_tracing/latest/contour_tracing/image/fn.single_l8_to_paths.html)

It needs the feature "image" so don't forget to change your Cargo.toml:
```
contour_tracing = { version = "*", features = ["image"] }
```

Please try this and don't hesitate to report some issues.
